# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'HomeIoT' do
    pod "GaugeKit"
end

target 'HomeIoT WatchKit App' do

end

target 'HomeIoT WatchKit Extension' do

end

